name: water_tracker
description: A Flutter app that tracks daily water intake and sends reminders

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^19.5.0
  permission_handler: ^12.0.1
  intl: ^0.20.2
  provider: ^6.1.1
  percent_indicator: ^4.2.2
  timezone: ^0.10.1 
  



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Android specific configuration
  module:
    androidX: true
    androidPackage: com.example.water_tracker
    androidMinSdkVersion: 21

  # For notification icons
  # flutter_local_notifications:
  #   android:
  #     icon: '@mipmap/ic_launcher'
